    spring:
      redis:
        host: redis
        port: 6379
      datasource:
        url: jdbc:postgresql://postgres-sql:5432/test
        username: username
        password: password
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
          hibernate:
            format_sql: true
      mail:
        host: smtp.gmail.com
        port: 587
        username: FILL_THIS
        password: FILL_THIS
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
    frontend:
      host: FILL_THIS